name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} 
             -p ${{ secrets.DOCKER_PWD }}

      # Runs a set of commands using the runners shell
      - name: Build Flask Image
        run: |
          docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
          
      - name: Publish Image to DockerRepo
        run: docker push $REPO
        
  redeploy:
    name: Redeploy - Webhook call
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_REDEPLOY }}
